# -*- coding: utf-8 -*-
"""Assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkSQyEgo_igM1qqOAJ9jZtN4bv8ID-sb
"""

# Importing all the required packages and libraries

import kagglehub
import tensorflow as tf
import numpy as np
import os
import glob
import cv2
from PIL import Image # Import Pillow for TIFF support
from skimage.io import imread # Using skimage for TIFF reading is often simpler than PIL/TF for this task
from skimage import color
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from skimage.feature import hog
from skimage.transform import resize
from sklearn.model_selection import GridSearchCV, train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
import matplotlib.pyplot as plt
import seaborn as sns

# Accessing the UC Merced Land Use Dataset Image Data
path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")

print("Path to dataset files:", path)

# 1. Preparing - X (Image Paths) and y (Labels)

X = [] # List to hold image file paths
y = [] # List to hold corresponding integer labels

# The 'path' variable points to the downloaded dataset's root
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# Get a list of all class/label directories from the dataset_base_path
class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])
label_map = {name: i for i, name in enumerate(class_dirs)}

print(f"Detected Classes: {class_dirs}")

# Verifying if we found the expected number of classes
if not class_dirs:
    print(f"Error: No class directories found in {dataset_base_path}. Please check the dataset structure.")

for class_name, label in label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    # Find all image files (assuming .tif or similar extensions)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # If no .tif files are found directly, we try a recursive search and then fallback to .jpg/.jpeg
    if not image_files:
        print(f"Warning: No .tif files found directly in {class_path}. Trying recursive search for .tif and then .jpg.")
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)
            if not image_files:
                image_files = glob.glob(os.path.join(class_path, "**", "*.jpeg"), recursive=True)
                if image_files:
                    print(f"Found .jpeg files in {class_path} after recursive search.")
                else:
                    print(f"No .tif, .jpg, or .jpeg files found in {class_path} after recursive search.")
            else:
                print(f"Found .jpg files in {class_path} after recursive search.")

    for file_path in image_files:
        X.append(file_path)
        y.append(label)

X = np.array(X)
y = np.array(y)

print(f"\nTotal images found: {len(X)}")
print(f"Labels assigned: {np.unique(y)}")

# Performing the stratified 3-Way Split (Train: 78%, Val: 12%, Test: 10%)

validation_ratio = 0.12 / 0.90

# Split 1: Test Set (10%)
# Stratify=y ensures class balance across the initial split.
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=42, stratify=y)

# Split 2: Validation Set (12%)
# Stratify=y_train_val ensures class balance in the final split.
X_train, X_validation, y_train, y_validation = train_test_split(X_train_val, y_train_val, test_size=validation_ratio, random_state=42, stratify=y_train_val)

# Validation
print("\n--- Final Split Sizes (Image Paths) ---")
total_samples = len(X)

# Training set (~78%)
train_len = len(X_train)
train_percent = (train_len / total_samples) * 100
print(f"Train Set: {train_len} paths ({train_percent:.2f}%))")

# Validation set (~12%)
val_len = len(X_validation)
val_percent = (val_len / total_samples) * 100
print(f"Validation Set: {val_len} paths ({val_percent:.2f}%))")

# Test set (~10%)
test_len = len(X_test)
test_percent = (test_len / total_samples) * 100
print(f"Test Set: {test_len} paths ({test_percent:.2f}%))")

# Hyperparameters
IMG_SIZE = 256  # UC Merced images are 256x256
NUM_CLASSES = len(class_dirs) # Dynamically set NUM_CLASSES based on detected directories
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

# Image Loading and Preprocessing Function
def parse_image(file_path, label):
    """Loads, decodes, resizes, and normalizes an image."""

    # Python function to handle image loading and decoding using PIL
    def _decode_image_py_func(path_tensor):
        path = path_tensor.numpy().decode('utf-8') # Convert TF tensor string to Python string

        try:
            img_pil = Image.open(path)

            # Ensure image is in RGB format
            if img_pil.mode == 'RGBA':
                img_pil = img_pil.convert('RGB')
            elif img_pil.mode == 'L': # Grayscale to RGB
                img_pil = img_pil.convert('RGB')
            elif img_pil.mode != 'RGB': # Handle other non-standard modes by converting to RGB
                 img_pil = img_pil.convert('RGB')

            img_np = np.array(img_pil)
        except Exception as e:
            # Fallback for robustness, though PIL should handle common TIFFs.
            print(f"Warning: PIL failed to load image {path} with error: {e}. Attempting tf.io.decode_image as fallback.")
            img_bytes = tf.io.read_file(path)
            img_np = tf.io.decode_image(img_bytes, channels=3, expand_animations=False).numpy()

        return img_np

    # Use tf.py_function to wrap the Python decoding logic
    img = tf.py_function(func=_decode_image_py_func, inp=[file_path],Tout=tf.uint8)
    # Set the shape explicitly. The dimensions (height, width) can vary before resize.
    img.set_shape([None, None, 3])

    # Resize the image
    img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])

    # Convert to float32 and normalize to [0, 1]
    img = tf.image.convert_image_dtype(img, tf.float32)

    # Convert the integer label to one-hot encoding for classification
    label = tf.one_hot(label, NUM_CLASSES)

    return img, label

# Dataset Creation Function
def make_dataset(X_paths, y_labels, is_training=False):
    """Creates a batched and optimized tf.data.Dataset."""

    # Create a dataset from the NumPy arrays of file paths and labels
    dataset = tf.data.Dataset.from_tensor_slices((X_paths, y_labels))

    # Apply the parsing function to every element in the dataset
    dataset = dataset.map(parse_image, num_parallel_calls=AUTOTUNE)

    if is_training:
        # For training: shuffle and apply data augmentation
        dataset = dataset.shuffle(buffer_size=1000) # Shuffle the dataset
        dataset = dataset.repeat() # Repeat the dataset indefinitely for Keras model.fit

    # Batch the elements
    dataset = dataset.batch(BATCH_SIZE)

    # Prefetch the next batch for optimization
    dataset = dataset.prefetch(AUTOTUNE)

    return dataset

# Create the final datasets for use in model.fit()
train_ds = make_dataset(X_train, y_train, is_training=True)
validation_ds = make_dataset(X_validation, y_validation, is_training=False)
test_ds = make_dataset(X_test, y_test, is_training=False)

# Validation Check

print("Final Dataset Pipeline Created")
for images, labels in train_ds.take(1):
    print(f"Batch Shape (Images): {images.shape} (Should be [BATCH_SIZE, {IMG_SIZE}, {IMG_SIZE}, 3])")
    print(f"Batch Shape (Labels): {labels.shape} (Should be [BATCH_SIZE, {NUM_CLASSES}])")
    print(f"Image Tensor Dtype: {images.dtype}")
    print(f"Label Tensor Dtype: {labels.dtype}")
    break

# Configuration
NUM_CLASSES_TO_USE = 8
validation_ratio = 0.12 / 0.90 # (Val % / Pool %)
RANDOM_STATE = 42

# Re-download the dataset path explicitly within this cell to ensure correctness
path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# 1. Data Loading, Filtering, and Labeling

X_all = [] # List to hold all image file paths
y_all = [] # List to hold all corresponding integer labels

class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])

# Filter the Data to ONLY 8 Classes
selected_classes = class_dirs[:NUM_CLASSES_TO_USE]
new_label_map = {name: i for i, name in enumerate(selected_classes)}

print(f"Total original classes: {len(class_dirs)}. Using the first 8 classes: {selected_classes}")

for class_name, new_label in new_label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # Robust file finding logic (as provided in the user's input)
    if not image_files:
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)

    for file_path in image_files:
        X_all.append(file_path)
        y_all.append(new_label)

X = np.array(X_all)
y = np.array(y_all)

print(f"Total images found for 8 classes: {len(X)}")

# 2. Stratified 3-Way Split (78/12/10)

# Split 1: Test Set (10%)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=RANDOM_STATE, stratify=y)

# Split 2: Validation and Training Sets
X_train, X_validation, y_train, y_validation = train_test_split(
    X_train_val, y_train_val, test_size=validation_ratio, random_state=RANDOM_STATE, stratify=y_train_val)

print(f"Train Set Size: {len(X_train)}, Validation Set Size: {len(X_validation)}, Test Set Size: {len(X_test)}")

# 3. Feature Extraction Function (3D Color Histogram)

def extract_features(image_path_list):
    """ Loads images and extracts features (3D Color Histogram) for SVM """
    feature_vectors = []
    bins = 8 # Number of bins for the histogram in each channel

    for path in image_path_list:
        try:
            img = imread(path)

            # Ensure the image is 3-channel (RGB)
            if img.ndim == 2:
                img = color.gray2rgb(img)
            elif img.shape[2] == 4:
                img = img[:, :, :3]

            img = cv2.resize(img, (256, 256))

            # Calculate the 3D histogram
            hist = cv2.calcHist([img], [0, 1, 2], None, [bins, bins, bins],[0, 256, 0, 256, 0, 256])

            # Normalize and flatten
            hist = hist / np.sum(hist)
            feature_vector = hist.flatten()
            feature_vectors.append(feature_vector)

        except Exception as e:
            # Handle potential loading/processing errors gracefully
            print(f"Skipping image {path} due to error: {e}")

    return np.array(feature_vectors)

print("\nExtracting features for Training data...")
X_train_features = extract_features(X_train)

print("Extracting features for Validation data...")
X_validation_features = extract_features(X_validation)

print("Extracting features for Test data...")
X_test_features = extract_features(X_test)

print(f"\nFeature vector shape (e.g., Train): {X_train_features.shape}")

# 4. SVM Training and Evaluation (RBF Kernel)

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_validation_scaled = scaler.transform(X_validation_features)
X_test_scaled = scaler.transform(X_test_features)

print("\nStarting SVM Training (RBF Kernel)")

# Define and Train the SVM Model
svm_model = SVC(kernel='rbf', C=10, gamma='scale', random_state=RANDOM_STATE)
svm_model.fit(X_train_scaled, y_train)

print("SVM Training Complete.")

# Evaluate the Model on the Validation Set
y_validation_pred = svm_model.predict(X_validation_scaled)
val_accuracy = accuracy_score(y_validation, y_validation_pred)

print("\n--- Validation Results (Preliminary Tuning) ---")
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")
print("\nClassification Report on Validation Set:")
print(classification_report(y_validation, y_validation_pred, target_names=selected_classes))

# Final Evaluation on the Test Set
y_test_pred = svm_model.predict(X_test_scaled)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("\n--- Test Results (Final Evaluation) ---")
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_test_pred, target_names=selected_classes))

# Calculate the Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred)
print("\n--- Confusion Matrix ---")
print(cm)

# Confusion Matrix using Seaborn for clarity

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Blues',            # Color map (change if you prefer a different one)
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for SVM (Test Set)')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

"""# Task
Perform hyperparameter tuning for the Support Vector Machine (SVM) model using `GridSearchCV`. Define a parameter grid for the `C` and `gamma` hyperparameters of the RBF kernel. After finding the best parameters, train a new SVM model with these optimal settings on `X_train_scaled` and `y_train`, then evaluate its performance on `X_test_scaled` and `y_test`, reporting the test accuracy, classification report, and the best parameters found.

## Define Parameter Grid for SVM

### Subtask:
Define a dictionary for the SVM hyperparameters, specifying the ranges for 'C' and 'gamma' to be searched during tuning.

**Reasoning**:
The subtask requires defining a dictionary for SVM hyperparameters, including specific ranges for 'C', 'gamma', and setting the kernel. This code block will create the `param_grid` dictionary as specified.

## Perform GridSearchCV for Hyperparameter Tuning

### Subtask:
Use GridSearchCV with the defined parameter grid and cross-validation on the scaled training data (`X_train_scaled`, `y_train`) to find the best SVM hyperparameters. This will identify the combination of `C` and `gamma` that yields the highest cross-validation score.

Reasoning: To perform hyperparameter tuning using GridSearchCV, I need to import GridSearchCV, instantiate an SVC model, initialize GridSearchCV with the model and parameter grid, and then fit it to the scaled training data.
"""

# Instantiate an SVM model for GridSearchCV
svm = SVC(random_state=RANDOM_STATE)

# Instantiate an Parameter Grid for the SVM model
param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

# Initialize GridSearchCV
grid_search = GridSearchCV(estimator=svm,
                           param_grid=param_grid,
                           cv=5, # 5-fold cross-validation
                           scoring='accuracy',n_jobs=-1,verbose=2) # Print progress

print("Starting GridSearchCV...")
# Fit GridSearchCV to the scaled training data
grid_search.fit(X_train_scaled, y_train)

print("GridSearchCV complete.")

print("\nBest parameters found by GridSearchCV:")
print(grid_search.best_params_)

print("\nBest cross-validation accuracy:")
print(f"{grid_search.best_score_:.4f}")

print("\n--- Training Final SVM Model with Best Parameters ---")

# Instantiate a new SVM model with the best parameters found by GridSearchCV
final_svm_model = SVC(kernel=grid_search.best_params_['kernel'],
                      C=grid_search.best_params_['C'],
                      gamma=grid_search.best_params_['gamma'],
                      random_state=RANDOM_STATE)

# Train the final model on the entire scaled training data
final_svm_model.fit(X_train_scaled, y_train)

print("Final SVM model training complete.")

# Make predictions on the scaled test data
y_test_pred_tuned = final_svm_model.predict(X_test_scaled)

# Evaluate the final model's performance on the test set
test_accuracy_tuned = accuracy_score(y_test, y_test_pred_tuned)

print("\n--- Test Results with Tuned SVM Model ---")
print(f"Test Accuracy (Tuned Model): {test_accuracy_tuned * 100:.2f}%")
print("\nClassification Report on Test Set (Tuned Model):")
print(classification_report(y_test, y_test_pred_tuned, target_names=selected_classes))

# Preparing the Confusion Matrix
cm_tuned = confusion_matrix(y_test, y_test_pred_tuned)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm_tuned)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm_tuned,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for Tuned SVM Model (Test Set)')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

"""## Summary:

The best parameters found for the Support Vector Machine (SVM) model using `GridSearchCV` were `C=100` and `gamma=0.001`, with an `rbf` kernel. The improved test accuracy of the model trained with these optimal settings is 75.00%.

### Key Findings
*   A parameter grid was defined for hyperparameter tuning, exploring `C` values of [0.1, 1, 10, 100, 1000] and `gamma` values of [1, 0.1, 0.01, 0.001, 0.0001], specifically for an 'rbf' kernel.
*   `GridSearchCV` identified the optimal SVM hyperparameters as `{'C': 100, 'gamma': 0.001, 'kernel': 'rbf'}`.
*   The best cross-validation accuracy achieved during the grid search with these parameters was approximately 0.7789.
*   The final SVM model, trained with the best parameters, achieved a test accuracy of 75.00% on the unseen test data.

### Insights or Next Steps
*   The hyperparameter tuning significantly improved model performance,
achieving a respectable 75% accuracy on the test set, indicating good generalization capabilities.
*   Further exploration could involve refining the parameter grid around the optimal values (e.g., `C` between 10 and 1000, `gamma` between 0.0001 and 0.01) or trying other kernels if performance is still not satisfactory.
"""

# Employing HoG for feature extraction, and then applying the SVM RBF Kernel

# Configuration
NUM_CLASSES_TO_USE = 8
validation_ratio = 0.12 / 0.90 # (Val % / Pool %)
RANDOM_STATE = 42

# Re-download the dataset path explicitly within this cell to ensure correctness
path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# 1. Data Loading, Filtering, and Labeling

X_all = [] # List to hold all image file paths
y_all = [] # List to hold all corresponding integer labels

class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])

# Filter the Data to ONLY 8 Classes
selected_classes = class_dirs[:NUM_CLASSES_TO_USE]
new_label_map = {name: i for i, name in enumerate(selected_classes)}

print(f"Total original classes: {len(class_dirs)}. Using the first 8 classes: {selected_classes}")

for class_name, new_label in new_label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # Robust file finding logic (as provided in the user's input)
    if not image_files:
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)

    for file_path in image_files:
        X_all.append(file_path)
        y_all.append(new_label)

X = np.array(X_all)
y = np.array(y_all)

print(f"Total images found for 8 classes: {len(X)}")

# 2. Stratified 3-Way Split (78/12/10)

# Split 1: Test Set (10%)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=RANDOM_STATE, stratify=y)

# Split 2: Validation and Training Sets
X_train, X_validation, y_train, y_validation = train_test_split(
    X_train_val, y_train_val, test_size=validation_ratio, random_state=RANDOM_STATE, stratify=y_train_val)

print(f"Train Set Size: {len(X_train)}, Validation Set Size: {len(X_validation)}, Test Set Size: {len(X_test)}")

def extract_hog_features(image_path_list, pixels_per_cell=(8, 8), cells_per_block=(2, 2)):
    """ Loads images and extracts HoG features for SVM """
    feature_vectors = []

    # Define the target size for consistent processing
    target_size = (256, 256)

    for path in image_path_list:
        try:
            # Load and resize the image
            img = imread(path)

            # Ensure the image is 3-channel (RGB) and convert to Grayscale for HoG
            if img.ndim == 2:
                img_resized = resize(img, target_size, anti_aliasing=True)
                img_gray = img_resized
            elif img.shape[2] >= 3:
                # Convert to RGB (if needed) and then to grayscale
                img_rgb = img[:, :, :3]
                img_resized = resize(img_rgb, target_size, anti_aliasing=True)
                img_gray = color.rgb2gray(img_resized)
            else:
                # Skip if image format is unexpected
                print(f"Skipping image {path}: Unexpected channel count.")
                continue

            # We use 'transform_sqrt=True' for better performance. HoG works by creating histograms of local gradient orientations.

            hog_features = hog(
                img_gray,
                orientations=9,
                pixels_per_cell=pixels_per_cell,
                cells_per_block=cells_per_block,
                transform_sqrt=True,
                feature_vector=True
            )

            feature_vectors.append(hog_features)

        except Exception as e:
            # Handle potential loading/processing errors gracefully
            print(f"Skipping image {path} due to error: {e}")

    return np.array(feature_vectors)

# 3. Feature Extraction Function (HoG)

# Use common HoG parameters: 9 orientations, 8x8 pixels per cell, 2x2 cells per block
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

print("\nExtracting features for Training data (HoG)...")
X_train_features = extract_hog_features(X_train, pixels_per_cell, cells_per_block)

print("Extracting features for Validation data (HoG)...")
X_validation_features = extract_hog_features(X_validation, pixels_per_cell, cells_per_block)

print("Extracting features for Test data (HoG)...")
X_test_features = extract_hog_features(X_test, pixels_per_cell, cells_per_block)

print(f"\nFeature vector shape (e.g., Train): {X_train_features.shape}")

# 4. SVM Training and Evaluation (RBF Kernel)

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_validation_scaled = scaler.transform(X_validation_features)
X_test_scaled = scaler.transform(X_test_features)

print("\nStarting SVM Training (RBF Kernel)")

# Define and Train the SVM Model
svm_model = SVC(kernel='rbf', C=10, gamma='scale', random_state=RANDOM_STATE)
svm_model.fit(X_train_scaled, y_train)

print("SVM Training Complete.")

# Evaluate the Model on the Validation Set
y_validation_pred = svm_model.predict(X_validation_scaled)
val_accuracy = accuracy_score(y_validation, y_validation_pred)

print("\n--- Validation Results (Preliminary Tuning) ---")
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")
print("\nClassification Report on Validation Set:")
print(classification_report(y_validation, y_validation_pred, target_names=selected_classes))

# Final Evaluation on the Test Set
y_test_pred = svm_model.predict(X_test_scaled)
test_accuracy = accuracy_score(y_test, y_test_pred)

print("\n--- Test Results (Final Evaluation) ---")
print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_test_pred, target_names=selected_classes))

# Preparing the Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for Tuned SVM Model (Test Set)')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

"""## Define Parameter Grid for SVM (HoG)

### Subtask:
Define a dictionary for the SVM hyperparameters, specifying the ranges for 'C' and 'gamma' to be searched during tuning, specifically for the RBF kernel.

## Perform GridSearchCV for Hyperparameter Tuning (HoG)

### Subtask:
Use GridSearchCV with the defined parameter grid and cross-validation on the scaled HoG training data (`X_train_scaled`, `y_train`) to find the best SVM hyperparameters. This will identify the combination of `C` and `gamma` that yields the highest cross-validation score for the HoG features.

**Reasoning**:
To perform hyperparameter tuning using GridSearchCV, I need to import GridSearchCV, instantiate an SVC model, initialize GridSearchCV with the model and parameter grid, and then fit it to the scaled training data with HoG features.
"""

RANDOM_STATE = 42 # Define RANDOM_STATE here

param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

print("Parameter grid for SVM tuning has been defined:")

# Configuration
NUM_CLASSES_TO_USE = 8
validation_ratio = 0.12 / 0.90 # (Val % / Pool %)

path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# 1. Data Loading, Filtering, and Labeling

X_all = [] # List to hold all image file paths
y_all = [] # List to hold all corresponding integer labels

class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])

# Filter the Data to ONLY 8 Classes
selected_classes = class_dirs[:NUM_CLASSES_TO_USE]
new_label_map = {name: i for i, name in enumerate(selected_classes)}

print(f"Total original classes: {len(class_dirs)}. Using the first 8 classes: {selected_classes}")

for class_name, new_label in new_label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # Robust file finding logic (as provided in the user's input)
    if not image_files:
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)

    for file_path in image_files:
        X_all.append(file_path)
        y_all.append(new_label)

X = np.array(X_all)
y = np.array(y_all)

print(f"Total images found for 8 classes: {len(X)}")

# 2. Stratified 3-Way Split (78/12/10)

# Split 1: Test Set (10%)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=RANDOM_STATE, stratify=y)

# Split 2: Validation and Training Sets
X_train, X_validation, y_train, y_validation = train_test_split(
    X_train_val, y_train_val, test_size=validation_ratio, random_state=RANDOM_STATE, stratify=y_train_val)

print(f"Train Set Size: {len(X_train)}, Validation Set Size: {len(X_validation)}, Test Set Size: {len(X_test)}")

def extract_hog_features(image_path_list, pixels_per_cell=(8, 8), cells_per_block=(2, 2)):
    """ Loads images and extracts HoG features for SVM """
    feature_vectors = []

    # Define the target size for consistent processing
    target_size = (256, 256)

    for path in image_path_list:
        try:
            # Load and resize the image
            img = imread(path)

            # Ensure the image is 3-channel (RGB) and convert to Grayscale for HoG
            if img.ndim == 2:
                img_resized = resize(img, target_size, anti_aliasing=True)
                img_gray = img_resized
            elif img.shape[2] >= 3:
                # Convert to RGB (if needed) and then to grayscale
                img_rgb = img[:, :, :3]
                img_resized = resize(img_rgb, target_size, anti_aliasing=True)
                img_gray = color.rgb2gray(img_resized)
            else:
                # Skip if image format is unexpected
                # print(f"Skipping image {path}: Unexpected channel count.")
                continue

            # Calculate the HoG descriptor
            hog_features = hog(
                img_gray,
                orientations=9,
                pixels_per_cell=pixels_per_cell,
                cells_per_block=cells_per_block,
                transform_sqrt=True,
                feature_vector=True # Ensure a flattened vector is returned
            )

            feature_vectors.append(hog_features)

        except Exception as e:
            # Handle potential loading/processing errors gracefully
            print(f"Skipping image {path} due to error: {e}")

    return np.array(feature_vectors)

# 3. Feature Extraction Function (HoG)

# Use common HoG parameters: 9 orientations, 8x8 pixels per cell, 2x2 cells per block
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

print("\nExtracting features for Training data (HoG)...")
X_train_features = extract_hog_features(X_train, pixels_per_cell, cells_per_block)

print("Extracting features for Validation data (HoG)...")
X_validation_features = extract_hog_features(X_validation, pixels_per_cell, cells_per_block)

print("Extracting features for Test data (HoG)...")
X_test_features = extract_hog_features(X_test, pixels_per_cell, cells_per_block)

print(f"\nFeature vector shape (e.g., Train): {X_train_features.shape}")

# 4. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_validation_scaled = scaler.transform(X_validation_features)
X_test_scaled = scaler.transform(X_test_features)

# Instantiate an SVM model for GridSearchCV (re-using the same settings as before, but a fresh instance)
svm = SVC(random_state=RANDOM_STATE)

# Initialize GridSearchCV
grid_search_hog = GridSearchCV(estimator=svm,
                           param_grid=param_grid,
                           cv=5, # 5-fold cross-validation
                           scoring='accuracy',
                           n_jobs=-1, # Use all available CPU cores
                           verbose=2) # Print progress

print("Starting GridSearchCV for HoG features...")
# Fit GridSearchCV to the scaled training data (HoG features)
grid_search_hog.fit(X_train_scaled, y_train)

print("GridSearchCV for HoG features complete.")

# 1. Retrieve the Best Parameters and Best Estimator
print("\n--- Best Model Parameters & Setup ---")
print(f"Best cross-validation score: {grid_search_hog.best_score_ * 100:.2f}%")
print("Best parameters found on the training set:")
print(grid_search_hog.best_params_)

# Get the optimal model (the one with the best parameters)
best_svm_model = grid_search_hog.best_estimator_

# 2. Evaluation on the Validation Set (Used to select the best model during the fit)

print("\n--- Validation Results (Best HoG + SVM Model) ---")

# Predict on the scaled validation data
y_validation_pred_best = best_svm_model.predict(X_validation_scaled)
val_accuracy_best = accuracy_score(y_validation, y_validation_pred_best)

print(f"Validation Accuracy: {val_accuracy_best * 100:.2f}%")
print("\nClassification Report on Validation Set:")
# The variable 'selected_classes' should contain the names of your 8 land-use classes.
print(classification_report(y_validation, y_validation_pred_best, target_names=selected_classes))

# 3. Final Evaluation on the Test Set

print("\n--- Test Results (Final Evaluation of Best HoG + SVM Model) ---")

# Predict on the scaled test data
y_test_pred_best = best_svm_model.predict(X_test_scaled)
test_accuracy_best = accuracy_score(y_test, y_test_pred_best)

print(f"Test Accuracy: {test_accuracy_best * 100:.2f}%")
print("\nClassification Report on Test Set:")
# The variable 'selected_classes' should contain the names of your 8 land-use classes.
print(classification_report(y_test, y_test_pred_best, target_names=selected_classes))

# Preparing the Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred_best)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for Tuned SVM Model (Test Set)')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

# PCA Dimensionality Reduction with HoG

from sklearn.decomposition import PCA

# Configuration
NUM_CLASSES_TO_USE = 8
validation_ratio = 0.12 / 0.90 # (Val % / Pool %)
RANDOM_STATE = 42

path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# 1. Data Loading, Filtering, and Labeling

X_all = [] # List to hold all image file paths
y_all = [] # List to hold all corresponding integer labels

class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])

# Filter the Data to ONLY 8 Classes
selected_classes = class_dirs[:NUM_CLASSES_TO_USE]
new_label_map = {name: i for i, name in enumerate(selected_classes)}

print(f"Total original classes: {len(class_dirs)}. Using the first 8 classes: {selected_classes}")

for class_name, new_label in new_label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # Robust file finding logic (as provided in the user's input)
    if not image_files:
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)

    for file_path in image_files:
        X_all.append(file_path)
        y_all.append(new_label)

X = np.array(X_all)
y = np.array(y_all)

print(f"Total images found for 8 classes: {len(X)}")

# 2. Stratified 3-Way Split (78/12/10)

# Split 1: Test Set (10%)
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=RANDOM_STATE, stratify=y)

# Split 2: Validation and Training Sets
X_train, X_validation, y_train, y_validation = train_test_split(
    X_train_val, y_train_val, test_size=validation_ratio, random_state=RANDOM_STATE, stratify=y_train_val)

print(f"Train Set Size: {len(X_train)}, Validation Set Size: {len(X_validation)}, Test Set Size: {len(X_test)}")

def extract_hog_features(image_path_list, pixels_per_cell=(8, 8), cells_per_block=(2, 2)):
    """ Loads images and extracts HoG features for SVM """
    feature_vectors = []

    # Define the target size for consistent processing
    target_size = (256, 256)

    for path in image_path_list:
        try:
            # Load and resize the image
            img = imread(path)

            # Ensure the image is 3-channel (RGB) and convert to Grayscale for HoG
            if img.ndim == 2:
                img_resized = resize(img, target_size, anti_aliasing=True)
                img_gray = img_resized
            elif img.shape[2] >= 3:
                # Convert to RGB (if needed) and then to grayscale
                img_rgb = img[:, :, :3]
                img_resized = resize(img_rgb, target_size, anti_aliasing=True)
                img_gray = color.rgb2gray(img_resized)
            else:
                # Skip if image format is unexpected
                # print(f"Skipping image {path}: Unexpected channel count.")
                continue

            # Calculate the HoG descriptor
            hog_features = hog(
                img_gray,
                orientations=9,
                pixels_per_cell=pixels_per_cell,
                cells_per_block=cells_per_block,
                transform_sqrt=True,
                feature_vector=True # Ensure a flattened vector is returned
            )

            feature_vectors.append(hog_features)

        except Exception as e:
            # Handle potential loading/processing errors gracefully
            print(f"Skipping image {path} due to error: {e}")

    return np.array(feature_vectors)

# 3. Feature Extraction Function (HoG)

# Use common HoG parameters: 9 orientations, 8x8 pixels per cell, 2x2 cells per block
pixels_per_cell = (8, 8)
cells_per_block = (2, 2)

print("\nExtracting features for Training data (HoG)...")
X_train_features = extract_hog_features(X_train, pixels_per_cell, cells_per_block)

print("Extracting features for Validation data (HoG)...")
X_validation_features = extract_hog_features(X_validation, pixels_per_cell, cells_per_block)

print("Extracting features for Test data (HoG)...")
X_test_features = extract_hog_features(X_test, pixels_per_cell, cells_per_block)

print(f"\nFeature vector shape (e.g., Train): {X_train_features.shape}")

# Define the target number of dimensions (k). Given the small dataset size, a fixed component count like 100 is generally safe.
k_components = 100
pca = PCA(n_components=k_components, random_state=RANDOM_STATE)

# Fit PCA ONLY on the Training Data feature - This learns the principal components that capture maximum variance in the training set.
X_train_features_reduced = pca.fit_transform(X_train_features)

# Transform the Validation and Test Data using the fitted PCA model
X_validation_features_reduced = pca.transform(X_validation_features)
X_test_features_reduced = pca.transform(X_test_features)

# Check the variance retained by the selected components
print(f"PCA reduced HoG features from {X_train_features.shape[1]} to {k_components} dimensions.")
print(f"Total variance retained by {k_components} components: {np.sum(pca.explained_variance_ratio_):.4f}")

# Reassign the feature variables to the reduced versions for the rest of the pipeline
X_train_features = X_train_features_reduced
X_validation_features = X_validation_features_reduced
X_test_features = X_test_features_reduced

print(f"New feature vector shape (e.g., Train): {X_train_features.shape}")

# Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_validation_scaled = scaler.transform(X_validation_features)
X_test_scaled = scaler.transform(X_test_features)

# Instantiate an SVM model for GridSearchCV
svm = SVC(random_state=RANDOM_STATE)

# Define parameter grid (assuming param_grid is defined globally or earlier)
param_grid = {
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf']
}

# Initialize GridSearchCV
grid_search_hog = GridSearchCV(estimator=svm,
                           param_grid=param_grid,
                           cv=5, # 5-fold cross-validation
                           scoring='accuracy',
                           n_jobs=-1, # Use all available CPU cores
                           verbose=2) # Print progress

print("\n--- Before GridSearchCV Fit ---")
print(f"Shape of X_train_scaled: {X_train_scaled.shape}")
print(f"Length of y_train: {len(y_train)}") # This is the crucial diagnostic print

print("Starting GridSearchCV for HoG features...")
# Fit GridSearchCV to the scaled training data (HoG features)
grid_search_hog.fit(X_train_scaled, y_train)

print("GridSearchCV for HoG features complete.")

# 1. Retrieve the Best Parameters and Best Estimator
print("\n--- Best Model Parameters & Setup ---")
print(f"Best cross-validation score: {grid_search_hog.best_score_ * 100:.2f}%")
print("Best parameters found on the training set:")
print(grid_search_hog.best_params_)

# Get the optimal model (the one with the best parameters)
best_svm_model = grid_search_hog.best_estimator_

# 2. Evaluation on the Validation Set (Used to select the best model during the fit)
print("\n--- Validation Results (Best HoG + SVM Model) ---")

# Predict on the scaled validation data
y_validation_pred_best = best_svm_model.predict(X_validation_scaled)
val_accuracy_best = accuracy_score(y_validation, y_validation_pred_best)

print(f"Validation Accuracy: {val_accuracy_best * 100:.2f}%")
print("\nClassification Report on Validation Set:")
print(classification_report(y_validation, y_validation_pred_best, target_names=selected_classes))

# 3. Final Evaluation on the Test Set
print("\n--- Test Results (Final Evaluation of Best HoG + SVM Model) ---")
y_test_pred_best = best_svm_model.predict(X_test_scaled)
test_accuracy_best = accuracy_score(y_test, y_test_pred_best)

print(f"Test Accuracy: {test_accuracy_best * 100:.2f}%")
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_test_pred_best, target_names=selected_classes))

# Preparing the Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred_best)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for SVM Model - Post PCA application')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

# LDA Dimensionality Reduction

print("\n--- 3b. Applying LDA for Dimensionality Reduction ---")

# LDA projects data onto a maximum of C - 1 dimensions, where C is the number of classes.
k_components = NUM_CLASSES_TO_USE - 1 # k = 7
lda = LDA(n_components=k_components)

# 1. Fit LDA ONLY on the Training Data AND its labels (y_train)
# LDA uses the class information to find the most discriminative axes.
X_train_features_reduced = lda.fit_transform(X_train_features, y_train)

# 2. Transform the Validation and Test Data using the fitted LDA model
X_validation_features_reduced = lda.transform(X_validation_features)
X_test_features_reduced = lda.transform(X_test_features)

print(f"LDA reduced HoG features from {X_train_features.shape[1]} to {k_components} dimensions.")

# Reassign the feature variables to the reduced versions for the rest of the pipeline
X_train_features = X_train_features_reduced
X_validation_features = X_validation_features_reduced
X_test_features = X_test_features_reduced

print(f"New feature vector shape (e.g., Train): {X_train_features.shape}")

# 4. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_features)
X_validation_scaled = scaler.transform(X_validation_features)
X_test_scaled = scaler.transform(X_test_features)

# Instantiate an SVM model for GridSearchCV
svm = SVC(random_state=RANDOM_STATE)

# Initialize GridSearchCV
grid_search_hog = GridSearchCV(estimator=svm,
                           param_grid=param_grid,
                           cv=5, # 5-fold cross-validation
                           scoring='accuracy',
                           n_jobs=-1, # Use all available CPU cores
                           verbose=2) # Print progress

print("Starting GridSearchCV for HoG features...")
# Fit GridSearchCV to the scaled training data (HoG features)
grid_search_hog.fit(X_train_scaled, y_train)

print("GridSearchCV for HoG features complete.")

# Retrieve the Best Parameters and Best Estimator
print("\n--- Best Model Parameters & Setup ---")
print(f"Best cross-validation score: {grid_search_hog.best_score_ * 100:.2f}%")
print("Best parameters found on the training set:")
print(grid_search_hog.best_params_)

# Get the optimal model (the one with the best parameters)
best_svm_model = grid_search_hog.best_estimator_

# 2. Evaluation on the Validation Set (Used to select the best model during the fit)
print("\n--- Validation Results (Best HoG + SVM Model) ---")

# Predict on the scaled validation data
y_validation_pred_best = best_svm_model.predict(X_validation_scaled)
val_accuracy_best = accuracy_score(y_validation, y_validation_pred_best)

print(f"Validation Accuracy: {val_accuracy_best * 100:.2f}%")
print("\nClassification Report on Validation Set:")
print(classification_report(y_validation, y_validation_pred_best, target_names=selected_classes))

# 3. Final Evaluation on the Test Set
print("\n--- Test Results (Final Evaluation of Best HoG + SVM Model) ---")

# Predict on the scaled test data
y_test_pred_best = best_svm_model.predict(X_test_scaled)
test_accuracy_best = accuracy_score(y_test, y_test_pred_best)

print(f"Test Accuracy: {test_accuracy_best * 100:.2f}%")
print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_test_pred_best, target_names=selected_classes))

# Preparing the Confusion Matrix
cm = confusion_matrix(y_test, y_test_pred_best)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for Tuned SVM Model - Post application of LDA')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()

# CNN for classifying all 21 classes

# Configuration
NUM_CLASSES_TO_USE = 21
RANDOM_STATE = 42
IMAGE_SIZE = 64  # Smaller size for initial CNN speed/training
CHANNELS = 3     # RGB images

# Re-download the dataset path explicitly within this cell to ensure correctness
path = kagglehub.dataset_download("abdulhasibuddin/uc-merced-land-use-dataset")
dataset_base_path = os.path.join(path, "UCMerced_LandUse", "Images")

# 1. Data Loading, Filtering, and Labeling (All 21 Classes)
X_all = [] # List to hold all image file paths
y_all = [] # List to hold all corresponding integer labels

class_dirs = sorted([d for d in os.listdir(dataset_base_path) if os.path.isdir(os.path.join(dataset_base_path, d))])

# Filter the Data to 21 Classes
selected_classes = class_dirs[:NUM_CLASSES_TO_USE]
new_label_map = {name: i for i, name in enumerate(selected_classes)}

print(f"Total classes found: {len(class_dirs)}. Using all {NUM_CLASSES_TO_USE} classes.")

for class_name, new_label in new_label_map.items():
    class_path = os.path.join(dataset_base_path, class_name)
    image_files = glob.glob(os.path.join(class_path, "*.tif"))

    # Robust file finding logic
    if not image_files:
        image_files = glob.glob(os.path.join(class_path, "**", "*.tif"), recursive=True)
        if not image_files:
            image_files = glob.glob(os.path.join(class_path, "**", "*.jpg"), recursive=True)

    for file_path in image_files:
        X_all.append(file_path)
        y_all.append(new_label)

X = np.array(X_all) # Image paths
y = np.array(y_all) # Integer labels

print(f"Total images found for 21 classes: {len(X)}") # Should be 2100 images

# 2. Stratified 3-Way Split (78/12/10)
validation_ratio = 0.12 / 0.90 # (Val % / Pool %)

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.10, random_state=RANDOM_STATE, stratify=y)
X_train, X_validation, y_train, y_validation = train_test_split(
    X_train_val, y_train_val, test_size=validation_ratio, random_state=RANDOM_STATE, stratify=y_train_val)

print(f"Train Set Size: {len(X_train)}, Validation Set Size: {len(X_validation)}, Test Set Size: {len(X_test)}")

def load_and_preprocess_images(image_path_list, target_size=(IMAGE_SIZE, IMAGE_SIZE)):
    """Loads, resizes, and normalizes images for CNN input."""
    images = []

    for path in image_path_list:
        try:
            img = imread(path)

            # Ensure 3 channels and resize
            if img.ndim == 2: # Grayscale
                img = color.gray2rgb(img)
            elif img.shape[2] == 4: # RGBA
                img = img[:, :, :3]

            # Use skimage resize as it's cleaner for raw loading
            resized_img = resize(img, target_size, anti_aliasing=True)

            # Normalize pixel values to [0, 1]
            # Since imread often returns uint8, we normalize to float
            images.append(resized_img.astype('float32'))

        except Exception as e:
            print(f"Skipping image {path} due to error: {e}")

    return np.array(images)

print("\nLoading and Preprocessing Images...")

# Load and process image data
X_train_data = load_and_preprocess_images(X_train)
X_validation_data = load_and_preprocess_images(X_validation)
X_test_data = load_and_preprocess_images(X_test)

# Convert labels to one-hot encoding (required for categorical cross-entropy loss)
y_train_one_hot = to_categorical(y_train, num_classes=NUM_CLASSES_TO_USE)
y_validation_one_hot = to_categorical(y_validation, num_classes=NUM_CLASSES_TO_USE)
y_test_one_hot = to_categorical(y_test, num_classes=NUM_CLASSES_TO_USE)

print(f"Train Data Shape: {X_train_data.shape}, Train Label Shape: {y_train_one_hot.shape}")

# 4. Define the CNN Model
def build_cnn_model(input_shape, num_classes):
    model = Sequential([
        # Block 1: Feature Learning
        Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        # Block 2: Deeper Feature Learning
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        # Block 3: Highest Level Features
        Conv2D(128, (3, 3), activation='relu'),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        # Classification Head
        Flatten(),
        Dense(512, activation='relu'),
        Dropout(0.5),
        # Output layer with softmax for multi-class probability distribution
        Dense(num_classes, activation='softmax')
    ])

    # Compile the model
    model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
    return model

input_shape = (IMAGE_SIZE, IMAGE_SIZE, CHANNELS)
cnn_model = build_cnn_model(input_shape, NUM_CLASSES_TO_USE)
cnn_model.summary()

# 5. Train the Model
print("\nStarting CNN Training...")

history = cnn_model.fit(X_train_data, y_train_one_hot,epochs=50,batch_size=32,validation_data=(X_validation_data, y_validation_one_hot),
    verbose=1)

print("\nCNN Training Complete.")

# 6. Final Evaluation on the Test Set
print("\n--- Test Results (Final CNN Evaluation) ---")

# Evaluate returns loss and metrics (accuracy in this case)
test_loss, test_accuracy = cnn_model.evaluate(X_test_data, y_test_one_hot, verbose=0)

print(f"Test Accuracy: {test_accuracy * 100:.2f}%")
print(f"Test Loss: {test_loss:.4f}")

# Generate classification report
y_pred_probs = cnn_model.predict(X_test_data)
y_pred_labels = np.argmax(y_pred_probs, axis=1)

print("\nClassification Report on Test Set:")
print(classification_report(y_test, y_pred_labels, target_names=selected_classes, zero_division=0))

# Preparing the Confusion Matrix
cm = confusion_matrix(y_test, y_pred_labels)

print("\n--- Confusion Matrix (Raw Data) - Tuned SVM Model ---")
print(cm)

plt.figure(figsize=(10, 7))
sns.heatmap(
    cm,
    annot=True,              # Show the values in the cells
    fmt='d',                 # Format as integers
    cmap='Greens',           # Using 'Greens' for visual distinction from the previous plot
    xticklabels=selected_classes, # Labels for the predicted classes (columns)
    yticklabels=selected_classes  # Labels for the true classes (rows)
)

plt.title('Confusion Matrix for CNN')
plt.ylabel('True Class')
plt.xlabel('Predicted Class')
plt.show()